#! /bin/sh
# ChangeLog is more or less available through CVS revision history
# there is no separate file telling what was changed line by line ...

exec lynx "http://cvs.savannah.nongnu.org/viewcvs/libfuse/?root=hurdextras"
